basePath: /
definitions:
  main.Item:
    properties:
      description:
        example: A random description
        type: string
      itemCode:
        example: A1B2C3
        type: string
      lineItemId:
        description: gorm.Model
        type: integer
      quantity:
        example: 1
        type: integer
    type: object
  main.Order:
    properties:
      customerName:
        example: Aditya Tekur
        type: string
      items:
        items:
          $ref: '#/definitions/main.Item'
        type: array
      orderId:
        description: gorm.Model
        example: 1
        type: integer
      orderedAt:
        example: "2019-11-09T21:21:46+00:00"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: aditek@gmail.com
    name: API Support
  description: This is a sample serice for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get details of all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Order'
            type: array
        "400":
          description: ""
      summary: Get details of all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create a new order with the input paylod
      parameters:
      - description: Create order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/main.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
        "400":
          description: ""
      summary: Create a new order
      tags:
      - orders
  /orders/{orderID}:
    delete:
      consumes:
      - application/json
      description: Delete an order
      parameters:
      - description: Get order
        in: path
        name: orderID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: Delete an order
      tags:
      - orders
    get:
      consumes:
      - application/json
      description: Get details of an order
      parameters:
      - description: Get order
        in: path
        name: orderID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Order'
            type: array
        "400":
          description: ""
      summary: Get details of an order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update a order with the input paylod
      parameters:
      - description: Update order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/main.Order'
      - description: Get orderID
        in: path
        name: orderID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
        "400":
          description: ""
      summary: Update a order
      tags:
      - orders
swagger: "2.0"
